In [2]:
import os, pickle, datetime
import pandas as pd

from pyhspf import WDMUtil

In [6]:
str_precip = 'siletz_HSPF_precip.csv'
str_pet = 'siletz_HSPF_PET.csv'
str_wdm = 'bigelk_in.wdm'
str_wdm_new = 'siletz.wdm'
str_dir_data = 'C:\\Users\\kbranna\\source\\repos\\odeqwdm\\odeqwdm'

In [15]:
# need to set variable for HSPF message file. WDMItil uses this file
cur_messagepath = os.path.join(str_dir_data, 'hspfmsg.wdm')

In [10]:
os.path.abspath(os.path.curdir)

'C:\\Users\\kbranna\\source\\repos\\odeqwdm\\odeqwdm\\notebooks'

In [8]:
df_prec = pd.read_csv(os.path.join(str_dir_data, str_precip))
df_prec.head()

,DATE,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,10/1/1986,2.73,1.79,1.46,1.27,1.57,1.11,0.86,0.86,0.88,0.95,1.0,0.93,0.85,0.89,0.77,0.92,0.76
1,10/2/1986,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.07,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00
2,10/3/1986,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00
3,10/4/1986,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00
4,10/5/1986,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00

In [9]:
df_pet = pd.read_csv(os.path.join(str_dir_data, str_pet))
df_pet.head()

,DAY,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,10/1/1986,1.756219,2.080046,2.078347,2.159070,2.084235,2.285215,2.156267,2.154882,2.200082,2.129127,2.271422,2.449238,2.613737,2.436347,2.377227,2.276597,2.650479
1,10/2/1986,2.142354,2.709350,2.718054,2.814164,2.702490,2.894784,2.699495,2.699381,2.872701,2.763593,2.849857,3.030385,3.244398,3.057538,3.011048,2.870041,3.277679
2,10/3/1986,2.607575,3.056800,3.049686,3.095101,3.010588,3.054026,2.825049,2.825291,3.016258,2.950159,2.876644,2.971985,3.131632,2.995864,2.946399,2.979465,3.082915
3,10/4/1986,3.487947,4.073175,4.020021,4.104732,3.954149,3.924501,3.684745,3.686558,4.050193,3.938097,3.694696,3.673034,3.847136,3.687777,3.593417,3.721796,3.644676
4,10/5/1986,3.092949,3.733967,3.717609,3.771163,3.655034,3.634736,3.488184,3.489853,3.817091,3.703161,3.485941,3.500526,3.698419,3.527253,3.465369,3.468434,3.551984

In [16]:
# create an instance of WDMUtil class
wdm = WDMUtil(verbose = True, messagepath = cur_messagepath)

Initializing WDM environment...

opening the message file
successfully opened message file

In [17]:
# create a new wdm file
wdm.open(str_wdm_new, 'w')

opened siletz.wdm as a new file

12

In [18]:
# take from pyHSPF test01.py example
#
# the first few test runs write data to the WDM files, but they assume the 
# datasets already exist so we need to create them. have a look at the test
# UCI files if you are curious

attributes = {'TCODE ': 4, 
              'TSSTEP': 1, 
              'TSTYPE': 'WTMP', 
              'TSFORM': 3,
              }

# what these attributes mean:
#
# the time series type for the first dataset is "WTMP" (water temperature)
# the time code is 4 (the units of the time step for the dataset are days)
# the time step is 1 (1 "unit" of the time step = 1 day)
# the time step form is 3 (the water temperature is a "state" variable 
# that does not depend on time step)
#
# the time step form is perhaps most difficult to understand. different 
# variables have different forms when they are discretized into time steps.
# the flow for a time step could represent the average value across the
# step, the value at the beginning or end, the average value, or the total
# value (this is perhaps most important)--thus for example if I say "the flow
# between 2 and 3 pm was 10 m3 is different than saying the flow at 3 pm was
# 10 m3 per hour. Given that context, HSPF groups all variables into one of
# three categories (the examples reference heat transfer concepts):

# TSFORM = 1 -- The mean value of a state variable (such as temperature)
# TSFORM = 2 -- The total flux across a time step (such as heat flux energy)
# TSFORM = 3 -- The value at the end of the time step (such as temperature)

In [20]:
# for precip and pet, the TSFORM  value would be 2 becuase it would be the total precip that occured over the time-step
attributes['TSFORM'] = 3
attributes['TSTYPE'] = 'PREC'
wdm.create_dataset(str_wdm_new, 11, attributes)
attributes['TSTYPE'] = 'PET'
wdm.create_dataset(str_wdm_new, 12, attributes)

creating DSN 11 in siletz.wdm
DSN 11 already exists
created new DSN 11
writing attributes to DSN 11
set TCODE  to 4
set TSSTEP to 1
set TSTYPE to PREC
set TSFORM to 3
creating DSN 12 in siletz.wdm
DSN 12 already exists
created new DSN 12
writing attributes to DSN 12
set TCODE  to 4
set TSSTEP to 1
set TSTYPE to PET
set TSFORM to 3

In [22]:
# close wdm file
wdm.close(str_wdm_new)

successfully closed file siletz.wdm